#!/bin/bash
#
# sync-mac-version.sh -- Derive the macOS app version from the single source of
# truth in Directory.Build.props and write it to a generated xcconfig that the
# Xcode project consumes (MARKETING_VERSION / CURRENT_PROJECT_VERSION).
#
# This is the macOS analogue of how build/version.rc derives the Windows binary
# version from Directory.Build.props. Run it after bumping the version in
# Directory.Build.props; make-release-mac.sh also runs it automatically.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PROPS="$ROOT/Directory.Build.props"
OUT="$ROOT/src/app_mac/xcconfig/version.xcconfig"

[[ -f "$PROPS" ]] || { echo "error: missing $PROPS" >&2; exit 1; }

num() { grep -oE "<$1>[0-9]+" "$PROPS" | grep -oE '[0-9]+' | head -1; }
MAJ="$(num AsbVersionMajor)"; MIN="$(num AsbVersionMinor)"
PATCHN="$(num AsbVersionPatch)"; REV="$(num AsbVersionRevision)"
[[ -n "$MAJ" && -n "$MIN" && -n "$PATCHN" && -n "$REV" ]] \
    || { echo "error: could not parse AsbVersion* from $PROPS" >&2; exit 1; }

SHORT="$MAJ.$MIN.$PATCHN"
FULL="$MAJ.$MIN.$PATCHN.$REV"

cat > "$OUT" <<EOF
// GENERATED by tools/sign/sync-mac-version.sh from Directory.Build.props.
// Do not edit — change the version in Directory.Build.props and re-run the script.
MARKETING_VERSION = $SHORT
CURRENT_PROJECT_VERSION = $FULL
EOF

echo "wrote $OUT  (MARKETING_VERSION=$SHORT, CURRENT_PROJECT_VERSION=$FULL)"
