# SPDX-License-Identifier: GPL-2.0
# Out-of-tree Kbuild for the dxgkrnl module — mirrors the in-tree
# drivers/hv/dxgkrnl/Makefile but routed through CONFIG_DXGKRNL=m and
# with an include path so <uapi/misc/d3dkmthk.h> resolves from the
# vendored copy under src/include/uapi/misc/.

obj-m += dxgkrnl.o
dxgkrnl-y := dxgmodule.o hmgr.o misc.o dxgadapter.o ioctl.o \
             dxgvmbus.o dxgprocess.o dxgsyncfile.o

ccflags-y += -I$(src)/include -include $(src)/dxgkrnl_compat.h
